version: 3.4.0
# version: 2.1

orbs:
    node: circleci/node@16.15.1
    # node: circleci/node@5.0.2
jobs:
    build:
        working_directory: ~/circleci_leapfrog_mobile/leapfrog-mobile-circleci
        macos:
            xcode: "13.3"
        # -e - Exit immediately if a command exits with a non-zero status.
        # -o - sets the pipefail option, causes the pipeline to return the exit status of the last command to exit with a non-zero status
        shell: /bin/bash --login -eo pipefail
        # parameters:
            # HOMEBREW_HOME:
                # type: env_var_name
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - "41:ac:2f:f0:26:27:bb:05:84:6d:ac:bf:a4:2e:09:42"
            # - node/install-packages:
            #   pkg-manager: yarn
            - run:
                  name: Install dependencies
                  command: |
                    whoami
                    cd
                    HOME_DIR=`pwd`
                    echo "HOME_DIR: "
                    echo $HOME_DIR
                    WORKSPACE=$HOME_DIR/circleci_leapfrog_mobile/leapfrog-mobile-circleci
                    ls
                    yarn install --flat --verbose --ignore-engines
                    yarn add -D babel-jest jest --ignore-engines
                    # PATH=${HOMEBREW}/bin:$PATH
                    # export PATH
                    IOS_TARGET_NAME="ShopYourWayMAX"            
            - run:
                name: Generate android build
                command: |
                    APP_BUILD_NUMBER=`curl -ks https://sywcstaging.searshc.com/appVersion/leapfrogDev.php?action=bumpUpVersion`
                    echo "APP_BUILD_NUMBER = $APP_BUILD_NUMBER"
                    echo " "
                    echo "==============================================="
                    echo "      GENERATE BUILD FOR ANDROID APP           "
                    echo "==============================================="
                    echo " "  
                    echo "Generating build from ${GIT_BRANCH} for firebase"
                    GIT_COMMIT_STATE="success"
                    GIT_STATUS_CONTEXT="Generate Android APK"
                    echo " "
                    echo ">>> Generating the APK"
                    pwd
                    cd android
                    pwd
                    sed -i '' "s|versionCode 2|versionCode ${APP_BUILD_NUMBER}|g" app/build.gradle
                    echo ">>> Updating versionCode to ${APP_BUILD_NUMBER}"
                    ./gradlew assembleDev
                    RESULT=$?
                    echo $RESULT                    
            - store_test_results:
                path: test-results/jest/result.xml
            # - store_artifacts:
            #    path: test-results
